apiVersion: apps/v1
kind: Deployment
metadata:
  name: test11
  labels:
    app: test11
  namespace: namespace-workflow-1709358109156
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test11
  template:
    metadata:
      labels:
        app: test11
    spec:
      containers:
        - name: test11
          image: cdacn.azurecr.io/dotnet111:latest
          ports:
            - containerPort: 5000