apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-course
  labels:
    app: dotnet-course
  namespace: demo-aks-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-course
  template:
    metadata:
      labels:
        app: dotnet-course
    spec:
      containers:
        - name: dotnet-course
          image: cdacn.azurecr.io/demo-1709362170553:latest
          ports:
            - containerPort: 5000