apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-deply-auto
  labels:
    app: azure-deply-auto
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1724737559373
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-deply-auto
  template:
    metadata:
      labels:
        app: azure-deply-auto
    spec:
      containers:
        - name: azure-deply-auto
          image: acrworkflow1724737559373.azurecr.io/image-workflow-1724737559373:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
