apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo2
  labels:
    app: dotnetdemo2
  namespace: namespace-workflow-1691234885026
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetdemo2
  template:
    metadata:
      labels:
        app: dotnetdemo2
    spec:
      containers:
        - name: dotnetdemo2
          image: cdacn.azurecr.io/dotnetdemo2-1691234885026:latest
          ports:
            - containerPort: 80