apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-auto1
  labels:
    app: azure-auto1
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1724738404227
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-auto1
  template:
    metadata:
      labels:
        app: azure-auto1
    spec:
      containers:
        - name: azure-auto1
          image: acrworkflow1724738404227.azurecr.io/image-workflow-1724738404227:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
