apiVersion: v1
kind: Service
metadata:
  name: azure-deply-auto
  namespace: namespace-workflow-1724737559373
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: azure-deply-auto
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000