apiVersion: v1
kind: Service
metadata:
  name: test11
  namespace: namespace-workflow-1709358109156
spec:
  type: LoadBalancer
  selector:
    app: test11
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000