apiVersion: v1
kind: Service
metadata:
  name: azure-auto1
  namespace: namespace-workflow-1724738404227
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: azure-auto1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000