apiVersion: v1
kind: Service
metadata:
  name: dotnetdemo2
  namespace: namespace-workflow-1691234885026
spec:
  type: LoadBalancer
  selector:
    app: dotnetdemo2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80